
version: 2

models:
  - name: raw_stg
    description: "Raw stg"
    columns:
      - name: id
      - name: chat_name
      - name: registration_dt
      - name: country
      - name: age

  - name: v_stg_user
    description: "Stg user"
    columns:
      - name: id
      - name: chat_name
      - name: registration_dt
      - name: country
      - name: age